seed: 42
num_updates: 1000
rollout_length: 128
#TODO: add an update_batch_size when it is vectorised for improved execution

# learning_rate: 5e-4
learning_rate: 2.5e-4
ppo_epochs: 4
num_minibatches: 4

num_envs: 4
num_evaluation: 20

gamma: 0.99 # Discounting factor.
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5

env_name: "SpaceInvaders-MinAtar"
# env_name: "MountainCar-v0" # does not work
# env_name: "Acrobot-v1"
# env_name: "CartPole-v1"
ANNEAL_LR: True
ACTIVATION: "tanh"
DEBUG: False
evaluation_greedy: False
num_eval_episodes: 5

logger:
  system_name: "PPO"
  base_exp_path: results
  json_path: ppo/testing
  # json_path: ~
  should_log: True
