seed: 42
total_training_steps: 8e6
rollout_length: 256

ewma_decay: 0.899

# learning_rate: 5e-4
learning_rate: 2.5e-4
ppo_epochs: 4
num_minibatches: 4

num_envs: 8
num_evaluation: 50

gamma: 0.99 # Discounting factor.
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5

# env_name: "Asterix-MinAtar"
# env_name: "Freeway-MinAtar"
env_name: "SpaceInvaders-MinAtar"
ANNEAL_LR: False
ACTIVATION: "tanh"
DEBUG: False
evaluation_greedy: False
num_eval_episodes: 5

logger:
  system_name: "ppo_ewma"
  base_exp_path: results
  json_path: ~
  should_log: True
