seed: 44
total_training_steps: 5e5
rollout_length: 128

learning_rate: 5e-4
ppo_epochs: 4
num_minibatches: 4

num_envs: 4
num_evaluation: 15

gamma: 0.99 # Discounting factor.
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5

# env_name: "Acrobot-v1"
env_name: "CartPole-v1"
ANNEAL_LR: False
ACTIVATION: "tanh"
DEBUG: False
evaluation_greedy: False
num_eval_episodes: 5

logger:
  system_name: "ppo"
  base_exp_path: results
  json_path: ~ # automatically sets path based on params
  should_log: True
